# Generated by Django 6.1.1 on 2026-10-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/users/profile_pics/', verbose_name='Profile Picture'),
        ),
    ]
