[project]
name = "backend"
version = "0.1.0"
description = "Blog Website for showcase"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dj-database-url>=3.1.2",
    "django>=6.1.1",
    "djangosecretkeyenv>=0.2.0",
    "psycopg2>=2.9.13",
    "python-decouple>=3.8",
]

[project.scripts]
backend = "manage:main"
startapp = "startapp:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
